# Generated by Django 5.1.2 on 2024-11-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
